Avoid naming conflicts
On macOS, clang raises the following build errors:

  src/disasm/disasm.h:93:36: error: redefinition of 'wait'
      mov, lea, nop, cbw, cwd, call, wait, pushf, popf, sahf, lahf, movs,
                                   ^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/wait.h:248:9: note: previous definition is here
  pid_t   wait(int *) __DARWIN_ALIAS_C(wait);
          ^
  In file included from src/disasm/debugger.c:25:
  src/disasm/disasm.h:272:3: error: incompatible pointer to integer conversion initializing 'int' with an expression of type 'pid_t (int *)' (aka 'int (int *)') [-Werror,-Wint-conversion]
  { wait },                       /* 0x9b */
    ^~~~
  src/disasm/disasm.h:272:3: error: initializer element is not a compile-time constant
  { wait },                       /* 0x9b */
    ^~~~
  3 errors generated.

To avoid naming conflicts, the identifier 'wait' is renamed.